version: '3.6'

services:
  db:
    image: mysql:latest
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mesh

networks:
  mesh:
    driver: bridge
