version: 2.1

executors:
  linux:
    machine:
      image: ubuntu-2204:2023.02.1
    resource_class: medium

jobs:
  swarm:
    executor: linux
    environment:
      CUSTOM_IMAGE_NAMETAG: kelvintaywl-cci/swarm-test
    steps:
      - checkout
      - run: docker info
      - run:
          name: Start Docker Swarm
          command: |
            docker swarm init
            docker stack deploy -c swarm.yaml app --with-registry-auth
      - run:
          name: Inspect containers
          command: |
            docker service ls
            docker ps
      - run:
          name: build image
          command: |
            docker build --tag $CUSTOM_IMAGE_NAMETAG .
      # at this point, the DB should be ready to connect
      - run:
          name: Spin up container to interact with DB
          command: |
            docker run --rm --network app_mesh $CUSTOM_IMAGE_NAMETAG mysql -h app_db -u root -e "CREATE DATABASE foobar default character set utf8mb4;"

            docker run --rm --network app_mesh $CUSTOM_IMAGE_NAMETAG mysql -h app_db -u root -D foobar -e "SELECT NOW();"
      - run: docker swarm leave --force

workflows:
  main:
    jobs:
      - swarm
