version: 2.1

executors:
  jdk-postgres:
    docker:
      - image: cimg/openjdk:17.0
      - image: cimg/postgres:14.7
        user: postgres
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"

jobs:
  fun-with-postgresql:
    executor: jdk-postgres
    resource_class: medium
    steps:
      - checkout
workflows:
  main:
    jobs:
      - fun-with-postgresql
