version: 2.1

executors:
  main:
    docker:
      - image: alienfast/ci-ruby:5.1.71
    resource_class: medium

jobs:
  swarm:
    parameters:
      swarm_address_pool:
        type: string
        default: '10.20.0.0/16'
    executor: main
    parallelism: 11
    environment:
      CUSTOM_IMAGE_NAMETAG: kelvintaywl-cci/swarm-test
    steps:
      - setup_remote_docker
      - checkout
      - run: docker info
      - run:
          name: Start Docker Swarm
          command: |
            docker swarm init --default-addr-pool '<< parameters.swarm_address_pool >>'
            docker stack deploy -c swarm.yaml app --with-registry-auth
      - run:
          name: Inspect containers
          command: |
            docker service ls
            docker ps
      - run:
          name: build image
          command: |
            docker build --tag $CUSTOM_IMAGE_NAMETAG .
      # at this point, the DB should be ready to connect
      - run:
          name: Spin up container to interact with DB
          command: |
            docker run --rm --network app_mesh $CUSTOM_IMAGE_NAMETAG mysql -h app_db -u root -e "CREATE DATABASE foobar default character set utf8mb4;"

            docker run --rm --network app_mesh $CUSTOM_IMAGE_NAMETAG mysql -h app_db -u root -D foobar -e "SELECT NOW();"
      - run: docker swarm leave --force

workflows:
  main:
    jobs:
      - swarm
