version: 2.1

jobs:
  fun-with-mysql:
    docker:
      - image: cimg/base:current
    resource_class: medium
    steps:
      - setup_remote_docker:
          version: 20.10.24
      - run: |
          docker run -d -p "3306:3306" -e 'MYSQL_ROOT_PASSWORD=supersecretpassword' cimg/mysql:8.0.33
          sleep 10
      - run:
          name: check our DB is ready!
          # Showcase a simple way to check on our server, besides dockerize
          command: |
            N=20
            while [ $N -gt 0 ]
            do
              if $(mysql -h 127.0.0.1 -u root -e "PING" > /dev/null); then
                echo "Connected to MySQL!"
                exit 0
              fi
              echo "Not connected; retrying"
              N=$(( $N - 1 ))
              sleep 1
            done
            exit 1
workflows:
  main:
    jobs:
      - fun-with-mysql
