version: 2.1

jobs:
  fun-with-mysql:
    docker:
      - image: cimg/base:stable
      - image: mysql:latest
        command: "--default-authentication-plugin=mysql_native_password"
        environment:
          - MYSQL_HOST: 127.0.0.1
          # these will be created by our dump.sql
          #  - MYSQL_USER: rails
          #  - MYSQL_PASSWORD: rails
          - MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    resource_class: medium
    steps:
      - checkout
      - run: |
          sudo apt-get update && sudo apt-get install -y mysql-client
      - run:
          name: check our DB is ready!
          # Showcase a simple way to check on our server, besides dockerize
          command: |
            N=8
            while [ $N -gt 0 ]
            do
              if $(nc -z 127.0.0.1 3306); then
                echo "Connected to MySQL!"
                exit 0
              fi
              echo "Not connected; retrying"
              N=$(( $N - 1 ))
              sleep 1
            done
            exit 1
      - run:
          name: feed our SQL files
          command: |
            echo "time to ingest these tasty SQL files!"
            mysql -h 127.0.0.1 -u root < dump.sql
            

workflows:
  main:
    jobs:
      - fun-with-mysql
