version: 2.1

executors:
  jdk-postgres:
    parameters:
      pg_img:
        type: string
      pg_user:
        type: string
    docker:
      - image: cimg/openjdk:17.0
      # no need to set user,
      # set specific Postgres password
      - image: postgres:14.7
        environment:
          POSTGRES_USER: admin
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: "foobar"

jobs:
  fun-with-postgresql:
    executor:
      name: jdk-postgres
      pg_img: cimg/postgres:14.7
      pg_user: postgres
    resource_class: medium
    steps:
      - checkout
workflows:
  main:
    jobs:
      - fun-with-postgresql
